name: Autumn-Dependencies
main: dev.dementisimus.autumn.dependencies.plugin.bukkit.AutumnDependenciesPlugin
version: ${project.version}
api-version: 1.17

author: dementisimus
website: dementisimus.dev

libraries:
  - org.mongodb:bson:${mongodb.version}
  - com.zaxxer:HikariCP:${HikariCP.version}
  - mysql:mysql-connector-java:${mysql-connector-java.version}
  - org.mongodb:mongodb-driver-reactivestreams:${mongodb.version}
  - org.xerial:sqlite-jdbc:${sqlite-jdbc.version}
