name: Bug Report
description: File a bug report
labels: [ "bug" ]
assignees:
  - dementisimus

body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!

  - type: dropdown
    id: module
    attributes:
      label: Module
      description: To what module does your bug report belong to?
      multiple: true
      options:
        - 'Paper'
        - 'Paper-API'
        - 'Common'
        - 'Common-API'
    validations:
      required: true

  - type: input
    id: module-section
    attributes:
      label: Module section
      description: What section of the previously chosen module does this bug report belong to?
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Tell us what should happen
    validations:
      required: true

  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: Tell us what happens instead of the expected behavior
    validations:
      required: true

  - type: textarea
    id: detailed-description
    attributes:
      label: Detailed Description
      description: Describe the bug detailed
      value: see Expected & Current Behavior above
    validations:
      required: false

  - type: textarea
    id: stacktraces-log-output
    attributes:
      label: Stacktraces / Log output
      description: If you encountered any stacktraces, or you simply want to add some log
      render: shell
    validations:
      required: false

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
    validations:
      required: true

  - type: input
    id: java-version
    attributes:
      label: Java version
      description: What version of Java are you using ('java -version' output) ?
    validations:
      required: false

  - type: dropdown
    id: database
    attributes:
      label: Database
      description: What database are you using?
      multiple: true
      options:
        - 'MongoDB'
        - 'MariaDB (MySQL)'
        - 'SQLite'
    validations:
      required: false

  - type: input
    id: database-version
    attributes:
      label: Database version
      description: What version(s) of the previously specified database(s) are you using?
    validations:
      required: false

  - type: input
    id: minecraft-version
    attributes:
      label: Minecraft version
      description: What version of Minecraft are you using ('/version' output)?
    validations:
      required: false

  - type: input
    id: autumn-version
    attributes:
      label: Autumn version
      description: What version of Autumn are you using ('/about Autumn' version output)?
    validations:
      required: true
