name: Enhancement Request
description: Request an enhancement
labels: [ "enhancement" ]
assignees:
  - dementisimus

body:
  - type: input
    id: module-section
    attributes:
      label: Module section
      description: What section Autumn does this enhancement request belong to?
    validations:
      required: true

  - type: textarea
    id: request-details
    attributes:
      label: Request details
      description: Try to explain your enhancement request and how it may improve Autumn
    validations:
      required: true
