name: Enhancement Request
description: Request an enhancement
labels: [ "enhancement" ]
assignees:
  - dementisimus

body:
  - type: dropdown
    id: module
    attributes:
      label: Module
      description: To what module does your enhancement request belong to?
      multiple: true
      options:
        - 'Bukkit'
        - 'Bukkit-API'
        - 'Bungee'
        - 'Bungee-API'
        - 'Velocity'
        - 'Velocity-API'
        - 'Common'
        - 'Common-API'
        - 'Dependencies'
    validations:
      required: true

  - type: input
    id: module-section
    attributes:
      label: Module section
      description: What section of the previously chosen module does this enhancement request belong to?
    validations:
      required: true

  - type: textarea
    id: request-details
    attributes:
      label: Request details
      description: Try to explain your enhancement request and how it may improve Autumn
    validations:
      required: true
