name: BukkitAutumn
main: dev.dementisimus.autumn.bukkit.plugin.AutumnPlugin
version: ${project.version}
api-version: 1.17
softdepend:
  - Autumn-Dependencies

author: dementisimus
website: dementisimus.dev

commands:
  language:
  lang: