name: build
on: [ push, workflow_dispatch ]

env:
  name: Autumn

jobs:
  build:
    strategy:
      matrix:
        platform: [ ubuntu-latest ]

    runs-on: ${{ matrix.platform }}
    name: ${{ matrix.platform }}

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup-jdk-21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ secrets.CACHE_KEY }}

      - name: build paper-nms
        run: mvn paper-nms:init -file plugin/pom.xml

      - name: prepare settings.xml for repo development
        if: endsWith(github.ref, '/develop')
        uses: s4u/maven-settings-action@v3.0.0
        with:
          servers: |
            [{
              "id": "dementisimus-repository-development",
              "username": "${{ secrets.MAVEN_NAME }}",
              "password": "${{ secrets.MAVEN_SECRET }}"
            }]

      - name: build & deploy development artifacts
        if: endsWith(github.ref, '/develop')
        uses: s4u/maven-settings-action@v3.0.0
        with:
          servers: |
            [{
              "id": "dementisimus-repository-development",
              "username": "${{ secrets.MAVEN_NAME }}",
              "password": "${{ secrets.MAVEN_SECRET }}"
            }]
        run: mvn package deploy -DdevelopmentArtifacts

      - name: prepare settings.xml for repo release
        if: endsWith(github.ref, '/main')
        uses: s4u/maven-settings-action@v3.0.0
        with:
          servers: |
            [{
              "id": "dementisimus-repository-release",
              "username": "${{ secrets.MAVEN_NAME }}",
              "password": "${{ secrets.MAVEN_SECRET }}"
            }]

      - name: build & deploy release artifacts
        if: endsWith(github.ref, '/main')
        run: mvn package deploy -DreleaseArtifacts
