name: build
on: [ push, workflow_dispatch ]

env:
  name: Autumn
  package: dev/dementisimus/autumn/

jobs:
  build:
    strategy:
      matrix:
        platform: [ ubuntu-latest ]

    runs-on: ${{ matrix.platform }}
    name: ${{ matrix.platform }}

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup-jdk-16
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'

      - name: cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ secrets.CACHE_KEY }}

      - name: evaluate project info
        run: |
          echo "version=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: build
        run: mvn -U clean package javadoc:javadoc --file pom.xml

      - name: pre-deploy
        run: |
          mkdir ./artifacts
          mkdir ./javadocs
          cp ./autumn-dependencies/target/autumn-dependencies-${{ env.version }}.jar ./artifacts/${{ env.package }}/autumn-dependencies/${{ env.version }}/
          cp ./autumn-dependencies/pom.xml ./artifacts/${{ env.package }}/autumn-dependencies/${{ env.version }}/autumn-dependencies-${{ env.version }}.pom
          cp ./autumn-dependencies/target/site/apidocs/. ./javadocs/${{ env.package }}/autumn-dependencies/${{ env.version }}/
          ls -R ./
