name: build
on: [ push, workflow_dispatch ]

env:
  name: Autumn

jobs:
  build:
    strategy:
      matrix:
        platform: [ ubuntu-latest ]

    runs-on: ${{ matrix.platform }}
    name: ${{ matrix.platform }}

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup-jdk-16
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'

      - name: cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ secrets.CACHE_KEY }}

      - name: evaluate project info
        run: |
          echo "version=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: build
        run: mvn -U clean package javadoc:javadoc --file pom.xml

      - name: pre-deploy
        run: |
          declare -a modules=("autumn-dependencies" "autumn-common-api" "autumn-common" "autumn-bukkit-api" "autumn-bukkit" "autumn-bungee-api" "autumn-bungee")

          for module in "${modules[@]}"; do
            fullModule=$module-${{ env.version }}
            package=dev/dementisimus/autumn/$module/${{ env.version }}
            artifactsTarget=./artifacts/$package
            javadocsTarget=./javadocs/$package

            mkdir -p $artifactsTarget
            mkdir -p $javadocsTarget

            cp ./$module/target/$fullModule.jar $artifactsTarget/
            cp ./$module/pom.xml $artifactsTarget/$fullModule.pom
            cp ./$module/target/site/apidocs/. $javadocsTarget/
          done
          ls -R ./
